---
- name: playbook.yml
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
   - name: install apache2
     apt:
       name: apache2
       state: latest
   - name: run apache2
     service:
        name: apache2
        state: started
   - name: create content
     copy:
        content: "Welcome to ANSIBLE!"
        dest: /var/www/html/index.html
